pull_request_rules:
  - name: Automatic merge dependabot prs
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - status-success~=.*1\.13.*
      - status-success~=.*1\.14.*
      - status-success~=.*1\.15.*
    actions:
      merge:
        method: merge